// Expo config plugin: silence warnings from third-party Pods.
//
// The native iOS project (ios/) is regenerated by `expo prebuild`, which wipes
// any manual Podfile edit. This plugin re-injects the warning-suppression loop
// into the Podfile's post_install hook on every prebuild, so the fix is durable
// and lives in version control.
//
// Scope: dependency (Pod) targets only — the app target keeps its own warnings.
//   - clang/Obj-C/C++: GCC_WARN_INHIBIT_ALL_WARNINGS = YES
//   - Swift:           OTHER_SWIFT_FLAGS += -suppress-warnings
const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// Presence of this build setting in the Podfile means we've already injected.
const MARKER = 'GCC_WARN_INHIBIT_ALL_WARNINGS';

const INJECT = `
    # --- Silence warnings from third-party code we don't own ---
    # Injected by plugins/withInhibitPodWarnings.js (survives expo prebuild).
    # 1) Pod targets: clang + Swift + libtool warnings.
    # 2) App target xcconfig: only the noise from importing third-party modules.
    installer.pods_project.targets.each do |pod_target|
      pod_target.build_configurations.each do |bc|
        bc.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        swift_flags = bc.build_settings['OTHER_SWIFT_FLAGS'] || '$(inherited)'
        swift_flags = swift_flags.join(' ') if swift_flags.is_a?(Array)
        unless swift_flags.include?('-suppress-warnings')
          bc.build_settings['OTHER_SWIFT_FLAGS'] = "#{swift_flags} -suppress-warnings"
        end
        libtool_flags = bc.build_settings['OTHER_LIBTOOLFLAGS'] || '$(inherited)'
        libtool_flags = libtool_flags.join(' ') if libtool_flags.is_a?(Array)
        unless libtool_flags.include?('-no_warning_for_no_symbols')
          bc.build_settings['OTHER_LIBTOOLFLAGS'] = "#{libtool_flags} -no_warning_for_no_symbols"
        end
      end
    end

    app_xcconfig_dir = File.join(installer.sandbox.root, 'Target Support Files', 'Pods-HudsonBusinessSolutions')
    Dir.glob(File.join(app_xcconfig_dir, '*.xcconfig')).each do |xcconfig|
      text = File.read(xcconfig)
      next if text.include?('-Wno-incomplete-umbrella')
      text = text.sub(/^(OTHER_CFLAGS = .*)$/) { "#{$1} -Wno-nullability-completeness -Wno-incomplete-umbrella -Wno-documentation" }
      text = text.sub(/^(OTHER_SWIFT_FLAGS = .*)$/) { "#{$1} -Xcc -Wno-nullability-completeness -Xcc -Wno-incomplete-umbrella -Xcc -Wno-documentation" }
      File.write(xcconfig, text)
    end
`;

module.exports = function withInhibitPodWarnings(config) {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const podfilePath = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      let contents = fs.readFileSync(podfilePath, 'utf8');

      // Idempotent: skip if already injected.
      if (contents.includes(MARKER)) {
        return cfg;
      }

      // Insert our loop immediately after the react_native_post_install(...) call.
      const anchor = /react_native_post_install\([\s\S]*?\n\s*\)\n/;
      if (!anchor.test(contents)) {
        // Podfile format changed — fail loud rather than silently skip.
        throw new Error(
          '[withInhibitPodWarnings] could not find react_native_post_install anchor in Podfile; ' +
            'update the plugin to match the new Expo Podfile template.',
        );
      }

      contents = contents.replace(anchor, (match) => `${match}${INJECT}`);
      fs.writeFileSync(podfilePath, contents);
      return cfg;
    },
  ]);
};
