import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F4F7FB',
  },
  authScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 20,
  },
  screenContent: {
    padding: 16,
    gap: 16,
  },
  authCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 20,
    borderWidth: 1,
    borderColor: '#D9E2EC',
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  heroCard: {
    backgroundColor: '#1E3A5F',
    borderRadius: 18,
    padding: 20,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#D9E2EC',
    gap: 10,
  },
  restrictedBanner: {
    backgroundColor: '#FFF7E6',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#F7D070',
    gap: 6,
  },
  restrictedBannerTitle: {
    color: '#7C5A03',
    fontSize: 16,
    fontWeight: '800',
  },
  restrictedBannerBody: {
    color: '#8D6E08',
    fontSize: 14,
    lineHeight: 20,
  },
  brandEyebrow: {
    color: '#F59E0B',
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  authTitle: {
    color: '#102A43',
    fontSize: 28,
    fontWeight: '800',
    marginTop: 8,
  },
  authSubtitle: {
    color: '#52606D',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
    marginBottom: 16,
  },
  fieldGroup: {
    marginBottom: 14,
    gap: 6,
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  label: {
    color: '#243B53',
    fontSize: 14,
    fontWeight: '700',
  },
  autoFilledBadge: {
    color: '#0F766E',
    fontSize: 12,
    fontWeight: '800',
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#BCCCDC',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#102A43',
    fontSize: 15,
  },
  inputAutoFilled: {
    borderColor: '#2F855A',
    backgroundColor: '#F0FFF4',
  },
  primaryButton: {
    backgroundColor: '#1E3A5F',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  primaryButtonCompact: {
    backgroundColor: '#1E3A5F',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 132,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  secondaryButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#BCCCDC',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  secondaryButtonText: {
    color: '#1E3A5F',
    fontSize: 14,
    fontWeight: '700',
  },
  secondaryActionButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#BCCCDC',
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 132,
  },
  secondaryActionButtonText: {
    color: '#1E3A5F',
    fontSize: 15,
    fontWeight: '700',
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  buttonRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 6,
  },
  helperText: {
    color: '#7B8794',
    fontSize: 13,
  },
  selectedTag: {
    color: '#0F766E',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 6,
  },
  alertTag: {
    color: '#B42318',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 4,
  },
  warningTag: {
    color: '#B54708',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 2,
  },
  loadingText: {
    marginTop: 12,
    color: '#52606D',
    fontSize: 15,
  },
  centeredState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  centeredStateCompact: {
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  headerCopy: {
    flex: 1,
  },
  screenTitle: {
    color: '#102A43',
    fontSize: 24,
    fontWeight: '800',
    marginTop: 4,
  },
  screenSubtitle: {
    color: '#52606D',
    fontSize: 14,
    marginTop: 2,
  },
  logoutButton: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9E2EC',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  logoutButtonText: {
    color: '#B42318',
    fontSize: 14,
    fontWeight: '700',
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: '#EAF1F7',
    borderRadius: 14,
    padding: 4,
    gap: 4,
    flexWrap: 'wrap',
  },
  tabButton: {
    flex: 1,
    minWidth: 88,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 10,
  },
  tabButtonActive: {
    backgroundColor: '#FFFFFF',
  },
  tabButtonText: {
    color: '#52606D',
    fontSize: 14,
    fontWeight: '700',
  },
  tabButtonTextActive: {
    color: '#1E3A5F',
  },
  listItem: {
    borderWidth: 1,
    borderColor: '#E4E7EC',
    borderRadius: 14,
    padding: 14,
    gap: 4,
  },
  listItemTitle: {
    color: '#102A43',
    fontSize: 16,
    fontWeight: '800',
  },
  listItemMeta: {
    color: '#52606D',
    fontSize: 13,
    lineHeight: 18,
  },
  emptyText: {
    color: '#7B8794',
    fontSize: 14,
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 8,
  },
  heroMeta: {
    color: '#D9E2EC',
    fontSize: 14,
    lineHeight: 20,
  },
  cardTitle: {
    color: '#102A43',
    fontSize: 18,
    fontWeight: '800',
  },
  cardBody: {
    color: '#52606D',
    fontSize: 14,
    lineHeight: 20,
  },
  detailRow: {
    color: '#243B53',
    fontSize: 14,
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  metricCard: {
    width: '48%',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E4E7EC',
    borderRadius: 14,
    padding: 12,
    gap: 4,
  },
  metricLabel: {
    color: '#52606D',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  metricValue: {
    color: '#102A43',
    fontSize: 18,
    fontWeight: '800',
  },
  metricValueSmall: {
    color: '#102A43',
    fontSize: 15,
    fontWeight: '800',
  },
  metricStrip: {
    flexDirection: 'row',
    gap: 10,
  },
  metricStripCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9E2EC',
    borderRadius: 14,
    padding: 12,
    gap: 4,
  },
  metricStripLabel: {
    color: '#7B8794',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  metricStripValue: {
    color: '#102A43',
    fontSize: 14,
    fontWeight: '800',
  },
  selectionBox: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E4E7EC',
    borderRadius: 14,
    padding: 14,
    gap: 4,
  },
  selectionLabel: {
    color: '#52606D',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  selectionValue: {
    color: '#102A43',
    fontSize: 16,
    fontWeight: '800',
  },
  selectionHelper: {
    color: '#7B8794',
    fontSize: 13,
    lineHeight: 18,
  },
  chipRow: {
    gap: 8,
    paddingRight: 8,
  },
  choiceChip: {
    borderWidth: 1,
    borderColor: '#BCCCDC',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
  },
  choiceChipActive: {
    backgroundColor: '#1E3A5F',
    borderColor: '#1E3A5F',
  },
  choiceChipText: {
    color: '#243B53',
    fontSize: 13,
    fontWeight: '700',
  },
  choiceChipTextActive: {
    color: '#FFFFFF',
  },
  receiptPreviewCard: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E4E7EC',
    borderRadius: 14,
    padding: 14,
    gap: 8,
  },
  receiptPreviewImage: {
    width: '100%',
    height: 220,
    borderRadius: 12,
    resizeMode: 'contain',
    backgroundColor: '#FFFFFF',
  },
  ocrStatusRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  statusPill: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
  },
  statusPillGood: {
    backgroundColor: '#ECFDF3',
    borderColor: '#ABEFC6',
  },
  statusPillNeutral: {
    backgroundColor: '#F8FAFC',
    borderColor: '#D9E2EC',
  },
  statusPillSecondary: {
    backgroundColor: '#F8FAFC',
    borderColor: '#D9E2EC',
  },
  statusPillText: {
    fontSize: 12,
    fontWeight: '800',
  },
  statusPillTextGood: {
    color: '#067647',
  },
  statusPillTextNeutral: {
    color: '#475467',
  },
  readinessBox: {
    backgroundColor: '#FFF7E6',
    borderWidth: 1,
    borderColor: '#F7D070',
    borderRadius: 14,
    padding: 14,
    gap: 4,
  },
});